-- Initial schema for jezik: courses, profiles, sessions, per-exercise progress,
-- append-only attempts log, and completed-lessons index. All user-owned tables
-- are guarded by RLS (user_id = auth.uid()). Content ids (exercise_id, lesson_id,
-- course_id) are plain text and mirror the ids in the client-side seed (data/seed.ts).

-- ==================================================================
-- courses (public-read)
-- ==================================================================

create table public.courses (
  id text primary key,
  source_language text not null,
  target_language text not null,
  title text not null
);

alter table public.courses enable row level security;

create policy "courses are public" on public.courses
  for select to anon, authenticated using (true);

insert into public.courses (id, source_language, target_language, title) values
  ('hr-from-en', 'en', 'hr', 'Croatian for English speakers');

-- ==================================================================
-- profiles (one row per auth.users, auto-populated by trigger)
-- ==================================================================

create table public.profiles (
  user_id uuid primary key references auth.users on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles: own row" on public.profiles
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ==================================================================
-- sessions (one row per lesson attempt)
-- ==================================================================

create table public.sessions (
  id uuid primary key,
  user_id uuid not null references auth.users on delete cascade,
  lesson_id text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index sessions_user_started_idx
  on public.sessions (user_id, started_at desc);

alter table public.sessions enable row level security;

create policy "sessions: own rows" on public.sessions
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ==================================================================
-- exercise_progress (Leitner state per learner-exercise)
-- ==================================================================

create table public.exercise_progress (
  user_id uuid not null references auth.users on delete cascade,
  exercise_id text not null,
  box smallint not null check (box between 1 and 5),
  next_due_session int not null,
  first_seen_session int not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, exercise_id)
);

alter table public.exercise_progress enable row level security;

create policy "exercise_progress: own rows" on public.exercise_progress
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ==================================================================
-- exercise_attempts (append-only log)
-- ==================================================================

create table public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  exercise_id text not null,
  correct boolean not null,
  session_id uuid references public.sessions on delete set null,
  created_at timestamptz not null default now()
);

create index exercise_attempts_user_created_idx
  on public.exercise_attempts (user_id, created_at desc);

create index exercise_attempts_user_exercise_idx
  on public.exercise_attempts (user_id, exercise_id, created_at desc);

alter table public.exercise_attempts enable row level security;

create policy "exercise_attempts: own rows" on public.exercise_attempts
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ==================================================================
-- completed_lessons
-- ==================================================================

create table public.completed_lessons (
  user_id uuid not null references auth.users on delete cascade,
  lesson_id text not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

alter table public.completed_lessons enable row level security;

create policy "completed_lessons: own rows" on public.completed_lessons
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
